### ISSUE TITLE
Error using cargo generate

### ISSUE THREAD

**Issue by carlomilanesi** [rust-github/rust-github.github.io#1]
If I run the following command on Linux:
cargo generate --git https://github.com/rust-github/template.git
and then I type a name, like "abcdefg", I get:
 Project Name: abcdefg
 Creating project called `abcdefg`...
Error: liquid:   --> 12:4
   |
12 | {% raw  %}␊
   |    ^-^
   |
   = Unknown tag.
  with:
    requested=raw
    available tags=
    available blocks=

**Comment by marcoieni** [comment]
You have to update cargo generate to the latest version, which is `0.5.1`.
I think that it's enough to run `cargo install cargo-generate`

You can run `cargo generate --version` to see your current version.

**Comment by carlomilanesi** [comment]
Ok. I had version 0.5.0. With version 0.5.1 it works.
